### ISSUE TITLE
Cantidad de Falsos negativos

### ISSUE THREAD

**Issue by lodurr** [maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-lodurr#1]
![imagen](https://user-images.githubusercontent.com/1824882/70100337-c7bf3300-1607-11ea-823b-61c5bf1f9bed.png)

![imagen](https://user-images.githubusercontent.com/1824882/70100390-f1785a00-1607-11ea-8604-25c3970e64a3.png)

He visto la cantidad de falsos positivos, estaba pensando con el landuse haciendo un intersect de las canteras y las zonas industriales, pero al no estar tan definidas ocurren problemas como el mostrado en las fotos. 
Alguna idea??

**Comment by geofis** [comment]
@lodurr, se me ocurren dos posibilidades:

1. Hacerle un buffer a las canteras lo suficientemente grande como para que caigan todos los falsos positivos. La anchura del buffer será algo con lo que habría que jugar, pero si quedan algunos falsos positivos, no será mayor problema.

2. Marcar las zonas de falsos positivos, usando un criterio de repetición. Habría que generar una cuadrícula regular para el país, de resolución menor que la de MODIS (es decir, de más de 250 m de lado), y agregar los puntos (se haría con `aggregate`). Toda celda (o conjunto de ellas vecinas) que contenga repeticiones de puntos por encima de un umbral arbitrario (elegido sobre la base de conocimiento de los datos), por ejemplo, `365*0.25` (un trimestre), considerar dicha celda como falso positivo. Un incendio puede durar 90 días, pero sería algo poco habitual.

3. Basado en lo anterior, en lugar de usar repetición, atributos del punto de calor, agregándolos sobre la cuadrícula regular. Un atributo que podría ser viable es la intensidad. Es probable que, en función de los atributos haya un patrón para los falsos positivos.

4. Usando la cuadrícula regular mencionada en 2, delimitar hotspots basados en variable de frecuencia de punto de calor.

Supongo que alguna de estas propuestas, o quizá una combinación de éstas, podría funcionar. En todo caso, será interesante conocer cómo lo resuelves.

**Comment by geofis** [comment]
Supongo que dejamos este *issue* abierto hasta tanto haya alguna solución.

**Comment by lodurr** [comment]
Primero que todo quería pedirle excusas puesto que mi trabajo no me habia permitido dedicarle un tiempo al proyecto.
Por otro lado he estado pensando en el tema de los falsos positivos y he hecho el buffer de 1.11 km (QGis) respecto al centro de las canteras y zonas industriales (basado en OSM) para lo cual se han ido bastante las concentraciones de puntos. 
Estoy analizando los puntos 2 y 3 sin embargo creo que seria idoneo hacerlo directamente en R y viene la pregunta. 
Subo toda la data que usaré para el proyecto? son casi 6gb. En tal caso como lo haria lo subo en zip y se descomprime en el servidor?
Otra pregunta que resulto analizando el landuse de OSM es que observo que hay muchos incendios en la zona de crops and farms por lo que no se si se podrían tomar como incendios forestales.

**Comment by geofis** [comment]
Bueno, respecto de tu pregunta, pienso que 6 GB es mucho, pero imagino que ese volumen contiene imágenes. ¿Es correcto? ¿Cuáles imágenes? ¿Quizá DEM? Creo que no es buena idea subirlas al servidor (si aún no las has subido), porque podrían ocupar mucho espacio allí. En todo caso, si supiera de qué se tratan dichos 6 GB quizá podría opinar mejor.

Si con ese buffer de 1.11 logras eliminar concentraciones de falsos negativos, genial. Imagino que vas a obtener un patrón de asociación, sin necesidad de tener que refinar mucho.

Puedes clasificar los incendios en función de si ocurren en zonas de cultivos o no, sólo necesitarías una imagen de cobertura de Hansen (aunque sólo tiene cobertura de 2000). En ese caso, podrías usar un umbral, por ejemplo, 15% de cobertura arbórea, y elegir sólo los puntos que ocurren en dicho porcentaje. Ahora bien, si no te quieres complicar con ello, pues sólo se trata de un ejercicio, filtra sólo los falsos negativos que se producen en industrias y listo.

**Comment by lodurr** [comment]
Si sr, (Aun no las he subido, he estado trabajando inicialmente con incendios y divisionRD), Entre ellas están. 
* Cobertura Arborea 194Mb
* DTM JAXA RD 1Gb
* Uso de Suelo 737Mb
* World Clim 1.77Gb 
Tenia el de OSM pero decidi no usarlo pq ya trabaje con el. 

Si realmente el buffer funciono mejor de lo que estaba esperando. Creo que por ahora no haré lo de la grilla.

Para la clasificacion tengo ladata de Hansen (194Mb) o la OSM tiene tambien una pequeña clasificación de crops o podría hacerlo por reservas naturales, pero no se si de esa manera se pierda la correlación por municipios vecinos.

**Comment by geofis** [comment]
Me parece que no necesitas el DTM de JAXA, porque es muy detallado. Puedes usar por ejemplo, el [MERIT DEM](http://hydro.iis.u-tokyo.ac.jp/~yamadai/MERIT_DEM/), si es que verdaderamente lo necesitas. Pero que quizá basta con usar dicha variables morfométricas calculadas por otros. Puedes usar mejor [Geomorpho90m](https://zenodo.org/record/1807119#.Xg9wWXUzb0o) como fuente de esa y otras variables. De WorldClim no creo que necesites todas las variables, pero quizá sólo usa algunas (como las medias) y sube sólo esas.

En general, te recomendaría que intentaras la parte de estadística zonal (resúmenes por áreas) en local, y luego sube los resultados (no los raster) al servidor, porque imagino que en tu PC será más rápido. En todo caso, si tuvieses problemas instalando paquetes, puedes usar el servidor, pero ya sabes que irá un poco lento.

Escribí una función de estadística zonal para objetos `sf` y `raster` [aquí](https://raw.githubusercontent.com/geofis/geomorpho90m-tools/master/estadistica_zonal_objetos.R), que quizá te sirva. También [esta otra](https://raw.githubusercontent.com/geofis/zonal-stats-sf/master/zonal-stats-sf.R) entre objetos `sf`

El uso del suelo, ¿de dónde proviene?

Con Hansen puedes clasificar, por ejemplo, usa un umbral de cobertura en la capa de cobertura de 2000 (treecover2000), y quedarte con los puntos de calor que caigan dentro de dicha máscara.

En ensayos que estoy haciendo para un manuscrito encuentro alta correlación con puntos de calor en cobertura 25% o mayor y pérdida de bosque.

**Comment by lodurr** [comment]
Ok, estaré revisando otras opciones para el tema de pendientes. y poder disminuir su peso.

Respecto a WorldClim estoyy pensando aun como hacer la correlación respecto a cual variable.

He estado trabajando en el servidor perfectamente hasta este momento (No me plotea nada de lo que genero - imagino esta con la memoria llena)

Perfecto estaré revisando la misma

El uso de suelo lo use para conocer los incendios forestales es de GlobCover2009 http://due.esrin.esa.int/page_globcover.php (hice un select entre 20 - 120 asumiendo que estos son las zonas boscosas y no de cultivos.

Si puede mirar el código que he hecho hasta ahora me gustaría conocer su opinion. (hasta el momento estoy trabajando con la estandarización de los datos y estaba comenzando la correlación cuando no funciono mas el plot)

Muchas gracias.

**Comment by lodurr** [comment]
envio el shape de incendios por correo por que no puedo subir nada por encima de 100 mb al github y el geopackage que se hace en QGis no me funciona.

**Comment by lodurr** [comment]
Value | Label
-- | --
11 | Post-flooding or irrigated croplands (or aquatic)
14 | Rainfed croplands
20 | Mosaic cropland (50-70%) / vegetation   (grassland/shrubland/forest) (20-50%)
30 | Mosaic vegetation (grassland/shrubland/forest) (50-70%) /   cropland (20-50%)
40 | Closed to open (>15%) broadleaved evergreen or   semi-deciduous forest (>5m)
50 | Closed (>40%) broadleaved deciduous forest (>5m)
60 | Open (15-40%) broadleaved deciduous forest/woodland (>5m)
70 | Closed (>40%) needleleaved evergreen forest (>5m)
90 | Open (15-40%) needleleaved deciduous or evergreen forest   (>5m)
100 | Closed to open (>15%) mixed broadleaved and needleleaved   forest (>5m)
110 | Mosaic forest or shrubland (50-70%) / grassland (20-50%)
120 | Mosaic grassland (50-70%) / forest or shrubland (20-50%)
130 | Closed to open (>15%) (broadleaved or needleleaved,   evergreen or deciduous) shrubland (<5m)
140 | Closed to open (>15%) herbaceous vegetation (grassland,   savannas or lichens/mosses)
150 | Sparse (<15%) vegetation
160 | Closed to open (>15%) broadleaved forest regularly flooded   (semi-permanently or temporarily) - Fresh or brackish water
170 | Closed (>40%) broadleaved forest or shrubland permanently   flooded - Saline or brackish water
180 | Closed to open (>15%) grassland or woody vegetation on   regularly flooded or waterlogged soil - Fresh, brackish or saline water
190 | Artificial surfaces and associated areas (Urban areas >50%)
200 | Bare areas
210 | Water bodies
220 | Permanent snow and ice
230 | No data (burnt areas, clouds,…)

**Comment by lodurr** [comment]
Estuve trabajando y adelantando el proyecto, ahora mismo tengo un problema sencillo que estare corrigiendo en unos momentos(lo deje como breakpoint por cansancio el sabado). Estuve observando que no hay correlacion espacial basado en los resultados estadisticos sin embargo quiero terminar el Lisa cluster para efectos del trabajo antes de hacer otras correlaciones. 

Creo que la correlacion espacial puede no existir debido a que las extensiones de area vs cantidad de incendios por ejemplo para el caso de San Juan es muy alta por lo que estaba pensando hacer un campo de incendios por area y analizarlo de tal manera si existe una correlacion directa.

Me gustaria saber si lo que estoy haciendo es correcto, por lo que si tiene un tiempo para revisar el codigo y mas aun los resultados le estare muy agradecido.

**Comment by geofis** [comment]
Vi el shape de incendios. Pone 2009-2019, supongo que ese archivo funde datos de MODIS y VIIRS, o quizá sólo MODIS.

En la selección de GlobCover2009, creo que son bosques del 30 al 120, porque el 20 parece cultivo.

Imagino que tu código está en el servidor, así que miraré allá y te daré una opinión general.

Lo de que no hay correlación espacial sería extraño. ¿Qué variable no te dio correlación espacial? Creo que si miro el script me aclaro sobe esto y sobre lo que me comentas de San Juan.

Te cuento cuando lo mire.

**Comment by geofis** [comment]
Visto el script. Está bastante bien Diego. Lo pude reproducir perfectamente.

Esta comprobación...

```
match(names(c(table(incendiosForestales$ENLACE))), as.character(munInc$ENLACE))==1:155
```

es útil hacerla (cae bien en la línea 119), aunque realmente había coincidencia. No suelo fiarme de los organizadores (tipo `arrange`).

Aquí (162-169) hay un error de unidades, puesto que para obtener Km2 se necesita dividir entre 1,000,000:

```
munIncPerc <- munInc %>%st_centroid() %>%  mutate( 
  'IncPercentage' = munInc$NumIncendios/sum(munInc$NumIncendios)*100,
  'IncPercentage_log' = log1p(munInc$NumIncendios/sum(munInc$NumIncendios)*100),
  'AreaKm2' = as.numeric((st_area(munInc)/1000000)),
  'IncXArea' = (munInc$NumIncendios/AreaKm2),
  'IncXArea_log' = log1p(munInc$NumIncendios/AreaKm2),
  x=unlist(map(geom,1)), y=unlist(map(geom,2)))  %>% 
  st_drop_geometry() 
```

Autocorrelación espacial hay, al menos la probabilidad de que no la haya es extremadamente baja:

```
(gmoranw <- moran.test(x = munIncPerc$'IncPercentage_log', listw = munInc.w.W ))

	Moran I test under randomisation

data:  munIncPerc$IncPercentage_log  
weights: munInc.w.W    

Moran I statistic standard deviate = 6.9272, p-value = 2.146e-12
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
      0.348674184      -0.006493506       0.002628733 
```

Nota también los outliers espaciales (municipios que se diferencian mucho de su entorno en el valor de la variable, que son los que tienen etiquetas):

![image](https://user-images.githubusercontent.com/13460617/71898910-e3e75000-3130-11ea-8a46-d50e22b3a995.png)

Y el mapa LISA al menos da resultado:

![image](https://user-images.githubusercontent.com/13460617/71898974-1002d100-3131-11ea-8c3f-b0fe9e9c4ed6.png)

Sugiero que continúes Diego, reúne tus covariables y ejecuta el modelo; a mí me parece que vas bien.

**Comment by lodurr** [comment]
Para la linea 119 hay alguna sugerencia?
En la 162-169 entiendo esta bien por que esta dividido por 1 millon
'AreaKm2' = as.numeric((st_area(munInc)/1000000)),

Si eso estuve mirando respecto a la autocorrelación, en el momento en el que escribi no habia hecho los clusters lisa por que tenia un error en el join.  Afortunadamente ud pudo revisarlo ya totalmente funcional.

**Comment by geofis** [comment]
Sobre la línea 119, como todo da `TRUE` al ejecutar `match(names(c(table(incendiosForestales$ENLACE))), as.character(munInc$ENLACE))==1:155`, se supone que puedes dar por válida la unión.

**Comment by lodurr** [comment]
Perfecto, voy a cerrar este issue que creo se salio del tema hace rato y en caso tal abrire otro con la duda emergente.
