### ISSUE TITLE
Problema asignacion de variables raster

### ISSUE THREAD

**Issue by lodurr** [maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-lodurr#2]
Tengo los incendios forestales con su fecha de adquisición y los raster por mes con un valor.
Lo que quiero hacer es asignar en una nueva columna "Wind" el dato basado en la fecha de adquisición, por ejemplo si la fecha del mes es 07, deberia usar el archivo w07 y asignar para ese punto dicho valor.
Entiendo que el raster:extract funciona como un join item por item. Por lo que no he tenido suerte para encontrar la manera 
Inicialmente lo hice de la siguiente manera
```
temp <- noquote(paste("t",format(as.Date(incendiosForestales$ACQ_DATE), "%m"),sep=""))
incWorldClim <- raster::extract(temp, incendiosForestales,sp=TRUE)
```

Lo que no funciono al ser una serie de datos y no un solo.

Intente de esta manera, Pero veo que no adiciona una variable por cada bucle sino solamente para el 12 en este caso.

```
for (i in 1:12){
    if (i  < 10){
      variable <- assign(paste("w0", i, sep = ""), raster(paste("data/WorldClim/Wind/RD_wc2.0_2.5m_wind_0",i,".tif", sep="")))
      zzzz <- zzzz  %>% raster::extract(variable, incendiosForestales,sp=TRUE)  
    }
    else {
      variable <- assign(paste("w", i, sep = ""), raster(paste("data/WorldClim/Wind/RD_wc2.0_2.5m_wind_",i,".tif", sep="")))
      zzzz <- zzzz  %>% raster::extract(variable, incendiosForestales,sp=TRUE)  
    }
}
```

Si por favor puede darme una manita con este tema.

**Comment by geofis** [comment]
Aquí aplica un índice vectorizado al estilo `*apply`, con la idea de evitar el bucle. Suele recomendarse esta alternativa con preferencia sobre el bucle `for`.

No controlo el detalle de la estructura de los objetos involucrados, pero es probable que el bucle `for`esté generando todos los resultados que has solicitado, pero quizá `i+1` está sustituyendo a `i`, por ejemplo, 12 está sustituyendo a 11. Lo resuelves usando `variable[i]`, pero también dependerá mucho de qué tipo de objeto sea variable. Prefiere una lista, y asegúrate de que, antes de iniciar el bucle, los objetos `variable` e `i` y cualquier otro implicado en la secuencia de asignaciones del bucle, sean nulos (e.g. `i <- NULL`, `variable <- list()`

Nuevamente, sin conocer el detalle de la estructura de los objetos, opino un poco en el aire sobre el hecho de que exista un `else`. No estoy seguro de que sea necesario, pero seguramente lo necesitas para que el buen funcionamiento del bucle.

En todo caso, sospecho que en este caso tendré que entrar en ayuda más específica, así que, si no consigues lo que buscas, no dudes en preguntarme, que prefiero meterme a fondo para que se consiga el resultado, y no quedarme en las ramas.

**Comment by lodurr** [comment]
Ok, me explico un poco mejor para ponerle en contexto.

Tengo la variable de incendios con fecha de adquisición la cual estoy adquieriendo asi 
`month <- format(as.Date(incendiosForestales$ACQ_DATE), "%m")
`
 esto me entrega un 01,02, ...., 12 dependiendo la  fecha de adquisición. 
Mi idea sería que cuando haga el extract del raster de worldclim, se haga por cada item de incendiosForestales basado el mes, Esto se debe a que worldclim me da el valor para cada mes. 
Por ejemplo si el item 132 tiene como mes es 02 se debe asignar el codigo que tiene el raster w02 

Estoy un poco enredado por que segun he probado el raster::extract lo hace para todas las columnas y no sabria como hacerlo individualmente.
Agradezco su ayuda

**Comment by geofis** [comment]
Perfecto, entiendo. Voy a mirar en tu cuenta del sevidor de RStudio e intentaré darte alguna ayuda.

**Comment by geofis** [comment]
Aparentemente resuelto. Hice unas pruebas, no en paralelo, y cada punto toma un segundo, aprox., y son ~47k puntos. Quizá tardaría unas 13 horas en una PC normal (estimado grueso), pero probaré en paralelo en una PC de mayores prestaciones que la portátil. El servidor RStudio sin duda reventaría.

**Comment by geofis** [comment]
En paralelo sólo toma 10% del tiempo respecto de no paralelo, en mi portátil. Es decir, 0.1 segundos por punto. Pero probaré en una PC con mayores prestaciones.

**Comment by geofis** [comment]
Listo.

Creé un script separado con el nombre `proyecto_comparar_y_consolidar_con_original.r` a partir de `proyecto.r` de las 8 am de esta mañana.

Míralo, la sentencia desde `## Not run:` hasta `## End(Not run)` ejecutaría la extracción de los datos de los rásters en los  ~47k puntos. Tomaría un estimado de entre 60 a 120 minutos en paralelo, dependiendo de las prestaciones de la PC. Vigilar la temperatura con `Psensor` por ejemplo. No ejecutar en el servidor.

Nota que hay un paquete añadido, y nota que añadí una variable, usando transformación *Tukey Ladder of Powers*, que sí cumple con el supuesto de normalidad.

**Comment by lodurr** [comment]
Ok, mil gracias, instalare R en el servidor de la oficina sin embargo veré como funciona en windows :( lastimosamente aca no tenemos linux en esta maquina. 
Tengo una pregunta, esto ser haría solo para los vientos, sin embargo son varias las variables climaticas, yo estaba pensando usar la temperatura y radiacion solar para completar el trabajo. Pero no se si sea buena idea basado el tiempo de proceso y el tiempo del proyecto. No se ud que me recomiende.

Por cierto vi el lisa cluster de Tukey Ladder of powers y realmente me gusto bastante el resultado donde vi un poco mas acorde los hotspots basandose en el analisis visual que habia hecho inicialmente en donde la mayor concentración esta en San Juan e Higuey.

**Comment by geofis** [comment]
De nada. No te preocupes, no lo instales. Lo correré en mi workstation. No quería hacerlo sin estar frente a ella, porque como se tomará un rato, quiero estar cerca para monitorear temperatura.

El script, tal como está ahora, lo hace tanto para viento, como para radiación solar y temperatura. Crea un raster stack con las 36 capas y de ellas saca las consultas.

**Comment by lodurr** [comment]
Yo lo hice de una manera menos óptima pero con un buen resultado. (Sin r)
Con QGis usando  un plug in llamado point sampling tool saque las 36 variables con el enlace, el mes y el unique value. Los exporte como csv y luego para cada variable hice un buscar en matriz usando Excel 
Como resultante tengo un csv con un enlace, mes, unique value, temp, srad y wind para cada valor acorde a su mes, creo que con eso podría hacer un join usando el sf de incendios forestales.

No se que opinión tenga.

**Comment by geofis** [comment]
Si funciona, está bien. Sin embargo, dicha alternativa tiene dos posibles inconvenientes:

1) No hace reproducible el script, aunque al menos sólo lo sería en una muy pequeña parte.
2) Si la consistencia no se mantiene, podría cometerse el error de asignar valores falsos valores de las capas WorldClim a los puntos de calor. Esto se resuelve haciendo un chequeo cruzado de varios casos, y comprobando si existe consistencia.

En todo caso, al romperse el flujo de código, lo mejor sería cruzar el resultado con el obtenido vía R.

Finalmente, obtuve el resultado que te dejé como RDS en tu carpeta de proyecto bajo el nombre `puntos_calor_fuegos_y_worldclim_viento_temp_radiacion.RDS`. Este archivo también debe ser comprobado por verificación cruzada.

**Comment by lodurr** [comment]
1. Si claro, es un gran problema (de cierta manera lo que hice fue para resolver pero como lo dije anteriormente no es la manera optima)
2. Si claro sin embargo hice un chequeo aleatorio y al parecer todo esta ok. Sin embargo si vi un par de N/A que al realizar el histograma me hacen ruido. (Estos mismos me daban al hacer el raster::extract con la capa w1)

Estoy totalmente de acuerdo y si me permite usare su codigo de la misma manera (con la advertencia) (Sin embargo no se si al realizar el knit muera el servidor)

Estaré realizando la comprobación respecto al join que hice para ver su fiabilidad 

Por otro lado estuve pensando agregar precipitación que pienso es una variable importante para analizar y me hizo falta.

**Comment by geofis** [comment]
Perfecto.

Cuando insertes el código en el RMD, envuélvelo en un bloque de código que contenga la opción `eval=FALSE`. Por ejemplo:

![image](https://user-images.githubusercontent.com/13460617/72388593-b84e0200-36fc-11ea-8eb0-fd88c6fc198c.png)

Mete en ese bloque de código todo aquello que no quieras que se ejecute.

La precipitación también se podría añadir. Estoy por crear una función que haga el trabajo más fácilmente. En todo caso, escrito ya el código, no cuesta nada añadir la variable que sea necesaria.

**Comment by lodurr** [comment]
Si claro, yo estoy sacando el extract de las precipitaciones para que no pesen tanto y poderlas manejar facilmente en el R.
Lo haré con el sistema de eval=FALSE para no tener inconveniente. 

Por otro lado quería preguntarle precisamente respecto a eso mismo.
En el esquema del trabajo usted puso un item para el script "debe ir el script completo" o se debe hacer dentro de la metodologia como hicimos las practicas y quitar ese apartado

**Comment by lodurr** [comment]
Estuve mirando el archivo `puntos_calor_fuegos_y_worldclim_viento_temp_radiacion.RDS` sin embargo entiendo toca hacer un mutate para hallar el valor final para cada variable cierto? 
Se me ocurre asignar NA = 0 y realizar un sum por cada set de variables. 

Si puede revisar en la linea 244 del proyecto.r es el resultado que tengo (entiendo con esto puedo trabajar para poder realizar los procesos geoestadisticos basados en estas variables worldClim 

Sin embargo se me presenta un problema que detallo en un nuevo issue debido su naturaleza totalmente diferente a este

**Comment by geofis** [comment]
Sobre la pregunta del script, si debe ir o no completo, dos opciones.

1) Lo vas desarrollando dentro del documento, usando echo=F si prefieres para que sólo se impriman las salidas y no el código, y al final lo pegas de manera íntegra en la sección del script reproducible con echo=T y eval=F.

2) Lo mismo que lo anterior, pero sin colocarlo al final, pero con la desventaja de que no se ve el código en un único lugar.

**Comment by lodurr** [comment]
Lo haré de la forma 1. Me parece que se ve mucho mejor.
