### ISSUE TITLE
Tamaño de Muestra demasiado grande

### ISSUE THREAD

**Issue by lodurr** [maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-lodurr#3]
Luego de realizado la asignación de variables raster por incendio. He querido estimar datos a groso modo, sin embargo me llevo la sorpresa que la muestra es muy grande. 
```
Error in shapiro.test(incForestWorldClim$temp) : 
  sample size must be between 3 and 5000
```
He pensado (ligeramente) como poder agruparlos sin embargo unicamente se me ocurre por mes puesto que asi los valores de worldclim no se verán tan afectados como si lo hiciese por municipio.

Pero haciendo un histograma rapido veo que marzo tiene mas de 10000 registros, volviendo al mismo punto.

Estaré analizando y de encontrar alguna opción la comentaré por este issue.

**Comment by lodurr** [comment]
Hice una media por cada uno de los municipios para cada variable, volviendo al punto de realizar el ánalisis por municipio

**Comment by geofis** [comment]
La prueba de Anderson-Darling podría ser útil:

```
> nortest::ad.test(rnorm(100000))

	Anderson-Darling normality test

data:  rnorm(1e+05)
A = 0.23175, p-value = 0.8019
```

 O la de Lilliefors:

```
> nortest::lillie.test(rnorm(10000))

	Lilliefors (Kolmogorov-Smirnov) normality test

data:  rnorm(10000)
D = 0.0089959, p-value = 0.066
```

El paquete `nortest` está instalado en el servidor.

Bien sobre la media.
