### ISSUE TITLE
Entrega Final

### ISSUE THREAD

**Issue by lodurr** [maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-lodurr#4]
Entrega Final realizada, sin embargo en el knit tuve algunos problemas con algunas imágenes lo que me gustaría resolver para obtener el producto final.

**Comment by lodurr** [comment]
Profe como esta, disculpe quería preguntarle si ud borrará estos repositorios de github mas adelante?? o podremos revisarlos luego?

**Comment by geofis** [comment]
No los borraré, puesto que son producción de ustedes. No sé qué decidirá GitHub en el futuro, pero espero que sean persistentes. De hecho, aunque el acceso al servidor está bloqueado, no borraré el contenido del servidor. Si lo borro, conservaré copia por algún tiempo.

**Comment by lodurr** [comment]
Ok perfecto, aun que realmente me refería a los de material de apoyo y asignaciones vistas en la clase.

**Comment by geofis** [comment]
Ah, sí, también los conservaré. Dependerá mucho de GitHub, pero los materiales quedarán disponibles.
